<?xml version="1.0"?>
<robot name="mighty" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--<xacro:arg name="model" default="Diff_Drive"/>
<xacro:include filename="$(find mighty_rover)/xacro/imu_macro.xacro" />-->
<!-- /////////////////////////////////////////////////////////////////-->

<!-- Include materials-->

<material name="Black">
   <color rgba="0.0 0.0 0.0 1.0"/>
</material>

<material name="White">
   <color rgba="1.0 1.0 1.0 1.0"/>
</material>

<!-- /////////////////////////////////////////////////////-->
<xacro:property name="origin" xyz="0 0 0" rpy="0 0 0" />

<!-- constants -->
<xacro:property name="deg_to_rad" value="0.017453"/>
<xacro:property name="PI" value="3.14"/>

<!-- base_link property -->
<xacro:property name="base_link_len" value=".19"/>
<xacro:property name="base_link_width" value=".19"/>
<xacro:property name="base_link_height" value="0.070"/>

<!-- wheel property -->
<xacro:property name="wheel_radius" value="0.055"/>
<xacro:property name="wheel_width" value="0.022"/>
<xacro:property name="wheel_height" value="0.11"/>
<xacro:property name="wheel_mass" value=".2"/>


<!-- /////////////////////////////////////////////////////-->
<xacro:macro name="cylinder_inertia" params ="m r h">
  <inertial>
   <mass value="${m}"/>
   <inertia ixx="${m*(3*r*r+h*h)/12}"  ixy="0.0" ixz="0.0"
            iyy="${m*(3*r*r+h*h)/12}"  iyz= "0.0"
            izz="${m*r*r/2}"/>
   </inertial>
</xacro:macro>

<!-- ///////////////////////////////////////////////////-->

<xacro:macro name= "inertial_matrix" params="mass">
  <inertial>
    <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" ixz="0.0"/>
   </inertial>
 </xacro:macro>

<!-- ////////////////////////////////////////////////////-->

<!--transmission block-->

<xacro:macro name="Transmission_block" params="joint_name">
   <transmission name="${joint_name}_trans">
    <type>transmission_interface/SimpleTransmission</type>
     <joint name="${joint_name}">
       <hardwareInterface>PositionJointInterface</hardwareInterface>
     </joint>
    <actuator name="${joint_name}_motor">
      <mechanicalReduction>1</mechanicalReduction>
     </actuator>
    </transmission>
 </xacro:macro>

<!-- //////////////////////////////////////////////////// -->

<!-- ////////////////////////////////////////////////////////////-->

<!-- base_link-->

 <link name="base_link">
    <visual>
      <origin rpy="-${PI/2} 0 ${PI/2}" xyz="0 0 0"/>
      <geometry>
         <mesh filename="package://diff_drive/meshes/base assembly.dae"/>
       </geometry>
     </visual>
    <collision>
      <origin rpy="-${PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://diff_drive/meshes/base assembly.dae"/>
      </geometry>
    </collision>
   <xacro:inertial_matrix mass="5.0"/>
 </link>

 <gazebo reference="base_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
<!-- ///////////////////      Wheels      ///////////////////////   -->

<xacro:macro name="wheel" params= "prefix suffix X Y Z">
  <link name= "${prefix}_${suffix}_wheel">
    <visual>
     <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
     <geometry><cylinder length="${wheel_width}" radius= "${wheel_radius/5}"/></geometry>
     <material name= "Black"/>
    </visual>
    <collision>
     <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
     <geometry><cylinder length="${wheel_width}" radius= "${wheel_radius/5}"/></geometry>
    </collision>
  <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius/3}" h="${wheel_width}"/>
  </link>
  


 <link name= "${prefix}_${suffix}_wheel1">
    <visual>
     <origin rpy= "0  ${PI/2} 0" xyz= "0 0 0"/>
     <geometry><mesh filename="package://diff_drive/meshes/tyre11.dae"/></geometry>
     <material name= "Black"/>
    </visual>
    <collision>
     <origin rpy= "0 ${PI/2} 0" xyz= "0 0 0"/>
     <geometry><mesh filename="package://diff_drive/meshes/tyre11.dae"/></geometry>
    </collision>
  <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>
      
  <gazebo reference ="${prefix}_${suffix}_wheel1">
     <material>Gazebo/Black</material>
     <turnGravityOff>false</turnGravityOff>
  </gazebo> 

  <joint name="${prefix}_${suffix}_wheel_joint1" type= "fixed">
    <parent link="${prefix}_${suffix}_wheel"/>
    <child link= "${prefix}_${suffix}_wheel1"/>
    <origin xyz="0 0 0"  rpy="0 0 0"/>
  </joint>



<gazebo reference ="${prefix}_${suffix}_wheel">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0"/>
    <kd value= "1.0"/>
    <material>Gazebo/Black</material>
</gazebo>

<joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
  <parent link= "base_link"/>
  <child link= "${prefix}_${suffix}_wheel"/>
  <origin xyz= "${0.062*X-0.058*Y} ${(base_link_len/2+0.02)*Z}  0.015" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <limit effort= "100" velocity="100"/>
  <dynamics damping="0.0" friction="0.0"/>  
</joint>

--

--

--

 <transmission name="${prefix}_${suffix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_${suffix}_wheel_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_${suffix}_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
 </transmission>
</xacro:macro>

<!--<xacro:macro name="body"parent="base_link" />
<xacro:wheel prefix="right" suffix="front" parent="base_link" X="1" Y="0" Z="-1"/>
<xacro:wheel prefix="right" suffix="back" parent="base_link" X="0" Y="1" Z="-1"/>
<xacro:wheel prefix="left" suffix="front" parent="base_link" X="1" Y="0" Z="1"/>
<xacro:wheel prefix="left" suffix="back" parent="base_link" X="0" Y="1" Z="1"/>-->

<xacro:wheel prefix="right" suffix="front" X="1" Y="0" Z="-1"/>
<xacro:wheel prefix="right" suffix="back" X="0" Y="1" Z="-1"/>
<xacro:wheel prefix="left" suffix="front" X="1" Y="0" Z="1"/>
<xacro:wheel prefix="left" suffix="back" X="0" Y="1" Z="1"/>

<!--///////////////////////////////////////////////////////////////// -->

<joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child  link="imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <link name="imu_link"/>
    <gazebo reference="imu_link">
      <gravity>true</gravity>
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>data</topic>
        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
          <topicName>imu/data</topicName>
          <bodyName>imu_link</bodyName>
          <updateRateHZ>10.0</updateRateHZ>
          <gaussianNoise>0.0</gaussianNoise>
          <xyzOffset>0 0 0</xyzOffset>
          <rpyOffset>0 0 0</rpyOffset>
          <frameName>imu_link</frameName>
        </plugin>
        <pose>0 0 0 0 0 0</pose>
      </sensor>
    </gazebo>


<!--link name="hokuyo_sensor">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
   <geometry>
     <box size="0.05 0.05 0.05"/>
   </geometry>
   <material name="Blue"/>
   </visual>
 </link>

<joint name="hokuyo_joint" type="fixed">
  <origin xyz="0.07 0 0.08" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="hokuyo_sensor"/>
</joint>

<gazebo reference="hokuyo_sensor">
  <material>Gazebo/Blue</material>
  <turnGravityOff>false</turnGravityOff>
  <sensor type="ray" name="base_link_hokuyo_sensor">
   <pose>0.025 0 0 0 0 0</pose>
   <visualize>false</visualize>
   <update_rate>40</update_rate>
   <ray>
     <scan>
       <horizontal>
         <samples>720</samples>
         <resolution>1</resolution>
         <min_angle>-1.57</min_angle>
         <max_angle>1.57</max_angle>  
        </horizontal>
      </scan>
     <range>
        <min>0.10</min>
        <max>10.0</max>
        <resolution>0.001</resolution>
      </range>
     </ray>
     <plugin name="gazebo_ros_head_hokuyo_controller" 
          filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_sensor</frameName>
       </plugin>
      </sensor>
     </gazebo-->   

  
<!-- //////////////////////////////////////////////////////////////// -->

  <xacro:include filename="$(find visual_test)/xacro/_d435.gazebo.xacro"/>

  <!--xacro:macro name="sensor_d435" params="name:=camera topics_ns:=camera parent *origin publish_pointcloud:=true"-->
    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  
    <!-- The following values model the aluminum peripherial case for the
    D435 camera, with the camera joint represented by the actual 
    peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/> <!--0.0149-->
  
    <!-- The following offset is relative the the physical D435 camera peripherial
    camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

    <material name="camera_aluminum">
    <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- camera body, with origin at bottom screw mount -->
    <joint name="camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="base_link"/>
      <child link="camera_bottom_screw_frame" />
    </joint>
    <link name="camera_bottom_screw_frame"/>

    <joint name="camera_link_joint" type="fixed">
      <origin xyz="0.08 ${d435_cam_depth_py} 0.055" rpy="0 0 0"/>
      <parent link="camera_bottom_screw_frame"/>
      <child link="camera_link" />
    </joint>

    <link name="camera_link">
      <visual>
      <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
          <mesh filename="package://realsense2_description/meshes/d435.dae" />
          <!--<mesh filename="package://realsense2_description/meshes/d435/d435.dae" />-->
        </geometry>
        <material name="camera_aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
        <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <!-- camera depth joints and links -->
    <joint name="camera_depth_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_link"/>
      <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_depth_frame" />
      <child link="camera_depth_optical_frame" />
    </joint>
    <link name="camera_depth_optical_frame"/>
      
    <!-- camera left IR joints and links -->
    <joint name="camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_left_ir_frame" />
    </joint>
    <link name="camera_left_ir_frame"/>

    <joint name="camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_left_ir_frame" />
      <child link="camera_left_ir_optical_frame" />
    </joint>
    <link name="camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_right_ir_frame" />
    </joint>
    <link name="camera_right_ir_frame"/>

    <joint name="camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_right_ir_frame" />
      <child link="camera_right_ir_optical_frame" />
    </joint>
    <link name="camera_right_ir_optical_frame"/>

    <!-- camera color joints and links -->
    <joint name="camera_color_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_color_frame" />
    </joint>
    <link name="camera_color_frame"/>

    <joint name="camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_color_frame" />
      <child link="camera_color_optical_frame" />
    </joint>
    <link name="camera_color_optical_frame"/>

      <!--xacro:gazebo_d435 camera_name="camera" reference_link="camera_link" topics_ns="camera" depth_optical_frame="camera_depth_optical_frame" color_optical_frame="camera_right_ir_optical_frame" infrared1_optical_frame="camera_left_ir_optical_frame" infrared2_optical_frame="camera_right_ir_optical_frame" publish_pointcloud="true"/-->

<!-- ros_control plugin-->

<!--gazebo>
   <plugin name="gazebo_ros_control" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>

      <updateRate>30</updateRate>
      <leftJoint>wheel_left_joint</leftJoint>
      <rightJoint>wheel_right_joint</rightJoint>
      <wheelSeparation>0.287</wheelSeparation>
      <wheelDiameter>0.066</wheelDiameter>
      <wheelAcceleration>1</wheelAcceleration>
      <wheelTorque>10</wheelTorque>
      <rosDebugLevel>na</rosDebugLevel>
   </plugin>
</gazebo-->
<gazebo>
  <plugin name="gazebo_ros_control" filename= "libgazebo_ros_control.so">
   <robotNamespace>/</robotNamespace>
  </plugin>
</gazebo>

</robot>
